### ISSUE TITLE
This SqlTransaction has completed; it is no longer usable

### ISSUE THREAD

**Issue by engineering87** [engineering87/OpenSharpTrace#3]
In high concurrency application contexts, the following error is encountered:

**System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.**

StackTrace:

```
      An exception occurred in the database while saving changes for context type 'OpenSharpTrace.Persistence.SQL.TraceContext'.
      System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
         at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck()
         at Microsoft.Data.SqlClient.SqlTransaction.Commit()
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

Transaction usage and rollback should be investigated.

**Comment by engineering87** [comment]
To be re-evaluated following pull request https://github.com/engineering87/OpenSharpTrace/pull/4
